console.log('Sentença');
{
    {
        console.log('Sentença');
        console.log('Sentença');
    }
}
$('body').fadeOut(1000);
$('body').fadeIn(2000);
$('$container').hide(1000);
$('$container').show(1000);